# https://conda-forge.org/docs/reference/runners/
github_actions_labels:       # [linux or win]
- depot-ubuntu-24.04-16      # [linux and x86_64]
- depot-ubuntu-24.04-arm-16  # [linux and aarch64]
- depot-windows-2025-16      # [win]
